#!/usr/local/bin/python3.4


##
## Practice Python Course: Exercise 18
## Bulls and Cows game
##
# Create a program that will play the “cows and bulls” game with the user. 
# The game works like this:
# 
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every 
# digit that the user guessed correctly in the correct place, they have a “cow”. 
# For every digit the user guessed correctly in the wrong place is a “bull.” 
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
# Once the user guesses the correct number, the game is over. Keep track of the number 
# of guesses the user makes throughout teh game and tell the user at the end.
# 
# Say the number generated by the computer is 1038. An example interaction could look 
# like this:
# 
#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

import random


def countCowsBulls(numba,rannum):
	print(rannum)
	print(numba)
	print('CowBulls eval processing....')
	cowbull = [0,0] #cows then bulls
	for n in range(len(numba)):
		if int(numba[n]) == int(rannum[n]):
			cowbull[0] += 1
		elif int(numba[n]) in rannum:
			cowbull[1] += 1
	if cowbull[0] == 4:
		print(str(cowbull[0]) + ' Cows ' + str(cowbull[1]) + ' Bulls')
		print("You guessed the correct number! You have won the game!")
		exit()
	else:
		return cowbull


def main():
	rannum = random.sample(range(1,9), 4)

	playing = True
	while playing:
		numba = input("Can you guess the 4-digit number? ")
		if numba == 'exit':
			print('Exiting program...')
			exit()
		elif len(numba) == 4:
			cowbullcount = countCowsBulls(numba,rannum)
			print(str(cowbullcount[0]) + ' Cows ' + str(cowbullcount[1]) + ' Bulls')
		else:
			print('Wrong input. Try again.')
			main()
		



if __name__ == "__main__":
	main()
	
exit()